const starter=[
{name:'Example player',team:'Team BDS',kills:42,deaths:31,wins:4,losses:2},
{name:'Example player 2',team:'G2 Esports',kills:39,deaths:29,wins:4,losses:2},
{name:'Example player 3',team:'Wolves Esports',kills:35,deaths:33,wins:3,losses:3},
{name:'Example player 4',team:'Virtus.pro',kills:31,deaths:36,wins:2,losses:4},
{name:'Example player 5',team:'FURIA',kills:28,deaths:34,wins:2,losses:4},
{name:'Example player 6',team:'Spacestation',kills:45,deaths:30,wins:5,losses:1},
{name:'Example player 7',team:'DarkZero',kills:37,deaths:32,wins:3,losses:3},
{name:'Example player 8',team:'M80',kills:26,deaths:35,wins:1,losses:5}
];
let players=JSON.parse(localStorage.getItem('r6-stage2-data')||'null')||starter.map(x=>({...x}));
const $=s=>document.querySelector(s); const num=v=>Math.max(0,Number(v)||0); const pct=p=>{const total=p.wins+p.losses;return total?Math.round(p.wins/total*100):0}; const kd=p=>p.deaths?(p.kills/p.deaths).toFixed(2):p.kills.toFixed(2);
function save(){localStorage.setItem('r6-stage2-data',JSON.stringify(players));localStorage.setItem('r6-stage2-time',new Date().toISOString());$('#saveStatus').textContent='Saved just now';$('#saveStatus').classList.add('save-flash');setTimeout(()=>$('#saveStatus').classList.remove('save-flash'),600);$('#lastSaved').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
function teams(){return [...new Set(players.map(p=>p.team).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function refreshTeams(){const select=$('#teamFilter'), old=select.value;select.innerHTML='<option value="all">All teams</option>'+teams().map(t=>`<option>${esc(t)}</option>`).join('');select.value=teams().includes(old)?old:'all'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){refreshTeams();const q=$('#search').value.toLowerCase(), team=$('#teamFilter').value, min=Number($('#minWin').value), sort=$('#sortBy').value;let rows=players.map((p,i)=>({...p,_i:i})).filter(p=>(!q||`${p.name} ${p.team}`.toLowerCase().includes(q))&&(team==='all'||p.team===team)&&pct(p)>=min);rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='kd'?Number(kd(b))-Number(kd(a)):sort==='winPct'?pct(b)-pct(a):b[sort]-a[sort]);$('#rowCount').textContent=rows.length;$('#empty').hidden=rows.length>0;$('#tableBody').innerHTML=rows.map((p,i)=>`<tr><td class="rank">${i+1}</td><td class="player-cell editable" contenteditable data-i="${p._i}" data-field="name">${esc(p.name)}</td><td class="team-cell editable" contenteditable data-i="${p._i}" data-field="team">${esc(p.team)}</td><td class="editable" contenteditable data-i="${p._i}" data-field="kills">${p.kills}</td><td class="editable" contenteditable data-i="${p._i}" data-field="deaths">${p.deaths}</td><td class="editable" contenteditable data-i="${p._i}" data-field="wins">${p.wins}</td><td class="editable" contenteditable data-i="${p._i}" data-field="losses">${p.losses}</td><td class="${pct(p)>=50?'positive':'neutral'}">${pct(p)}%</td><td class="${Number(kd(p))>=1?'positive':'neutral'}">${kd(p)}</td><td><button class="delete" data-delete="${p._i}" title="Delete player">×</button></td></tr>`).join('');renderSummary()}
function renderSummary(){const total=players.length,kills=players.reduce((a,p)=>a+p.kills,0),wins=players.reduce((a,p)=>a+p.wins,0),losses=players.reduce((a,p)=>a+p.losses,0),top=[...players].sort((a,b)=>pct(b)-pct(a))[0];$('#summary').innerHTML=`<div class="stat-card"><div class="stat-label">Players tracked</div><div class="stat-value">${total}</div><div class="stat-foot">Across ${teams().length} teams</div></div><div class="stat-card"><div class="stat-label">Total kills</div><div class="stat-value">${kills}</div><div class="stat-foot">Editable as matches finish</div></div><div class="stat-card"><div class="stat-label">Team win rate</div><div class="stat-value">${wins+losses?Math.round(wins/(wins+losses)*100):0}%</div><div class="stat-foot">${wins} wins · ${losses} losses</div></div><div class="stat-card"><div class="stat-label">Current leader</div><div class="stat-value" style="font-size:20px">${esc(top?.name||'—')}</div><div class="stat-foot">${top?pct(top):0}% win rate</div></div>`}
function csv(){return ['name,team,kills,deaths,wins,losses',...players.map(p=>[p.name,p.team,p.kills,p.deaths,p.wins,p.losses].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n')}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];return lines.slice(1).map(line=>{const vals=[...line.matchAll(/(?:^|,)\s*(?:"((?:[^"]|"")*)"|([^,]*))/g)].map(m=>(m[1]??m[2]??'').replaceAll('""','"').trim());return{name:vals[0]||'Unnamed player',team:vals[1]||'Unassigned',kills:num(vals[2]),deaths:num(vals[3]),wins:num(vals[4]),losses:num(vals[5])}}).filter(p=>p.name)}
$('#tableBody').addEventListener('focusout',e=>{if(!e.target.matches('.editable'))return;const i=Number(e.target.dataset.i),field=e.target.dataset.field;let v=e.target.textContent.trim();players[i][field]=['kills','deaths','wins','losses'].includes(field)?num(v):v;save();render()});$('#tableBody').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;players.splice(Number(b.dataset.delete),1);save();render()});['search','teamFilter','minWin','sortBy'].forEach(id=>$('#'+id).addEventListener('input',render));document.querySelectorAll('th[data-key]').forEach(th=>th.addEventListener('click',()=>{$('#sortBy').value=th.dataset.key;render()}));$('#clearFilters').onclick=()=>{$('#search').value='';$('#teamFilter').value='all';$('#minWin').value='0';$('#sortBy').value='winPct';render()};$('#addBtn').onclick=()=>{players.unshift({name:'New player',team:'New team',kills:0,deaths:0,wins:0,losses:0});save();render();setTimeout(()=>document.querySelector('.editable')?.focus(),50)};$('#resetBtn').onclick=()=>{if(confirm('Reset to the starter rows? Your current local edits will be replaced.')){players=starter.map(x=>({...x}));save();render()}};$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv()],{type:'text/csv'}));a.download='r6-stage-2-leaderboard.csv';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const data=parseCSV(r.result);if(data.length){players=data;save();render()}else alert('That CSV did not contain any player rows.')};r.readAsText(f);e.target.value=''};const saved=localStorage.getItem('r6-stage2-time');if(saved)$('#lastSaved').textContent=new Date(saved).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});render();
