const starter=[
{name:'Example player',team:'Team BDS',kills:42,deaths:31,wins:4,losses:2},
{name:'Example player 2',team:'G2 Esports',kills:39,deaths:29,wins:4,losses:2},
{name:'Example player 3',team:'Wolves Esports',kills:35,deaths:33,wins:3,losses:3},
{name:'Example player 4',team:'Virtus.pro',kills:31,deaths:36,wins:2,losses:4},
{name:'Example player 5',team:'FURIA',kills:28,deaths:34,wins:2,losses:4},
{name:'Example player 6',team:'Spacestation',kills:45,deaths:30,wins:5,losses:1},
{name:'Example player 7',team:'DarkZero',kills:37,deaths:32,wins:3,losses:3},
{name:'Example player 8',team:'M80',kills:26,deaths:35,wins:1,losses:5}
];
const $=s=>document.querySelector(s), num=v=>Math.max(0,Number(v)||0), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pct=p=>{const n=p.wins+p.losses;return n?Math.round(p.wins/n*100):0}, kd=p=>p.deaths?(p.kills/p.deaths).toFixed(2):p.kills.toFixed(2), dateNow=()=>new Date().toISOString().slice(0,10);
let state=JSON.parse(localStorage.getItem('r6-stage2-v2')||'null')||{players:starter.map(x=>({...x})),matches:[]}, history=[];
function snapshot(){history.push(JSON.stringify(state));if(history.length>20)history.shift();$('#undoBtn').disabled=false}
function save(){localStorage.setItem('r6-stage2-v2',JSON.stringify(state));localStorage.setItem('r6-stage2-time',new Date().toISOString());$('#saveStatus').textContent='Saved just now';$('#saveStatus').classList.add('save-flash');setTimeout(()=>$('#saveStatus').classList.remove('save-flash'),700);$('#lastSaved').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function teams(){return [...new Set(state.players.map(p=>p.team).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function refreshTeams(){const s=$('#teamFilter'),old=s.value;s.innerHTML='<option value="all">All teams</option>'+teams().map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');s.value=teams().includes(old)?old:'all'}
function renderSummary(){const ps=state.players, kills=ps.reduce((a,p)=>a+p.kills,0),w=ps.reduce((a,p)=>a+p.wins,0),l=ps.reduce((a,p)=>a+p.losses,0),top=[...ps].sort((a,b)=>pct(b)-pct(a)||Number(kd(b))-Number(kd(a)))[0];$('#summary').innerHTML=`<div class="stat-card"><div class="stat-label">Players tracked</div><div class="stat-value">${ps.length}</div><div class="stat-foot">Across ${teams().length} teams</div></div><div class="stat-card"><div class="stat-label">Total kills</div><div class="stat-value">${kills}</div><div class="stat-foot">${state.matches.length} logged performances</div></div><div class="stat-card"><div class="stat-label">Overall win rate</div><div class="stat-value">${w+l?Math.round(w/(w+l)*100):0}%</div><div class="stat-foot">${w} wins · ${l} losses</div></div><div class="stat-card"><div class="stat-label">Current leader</div><div class="stat-value" style="font-size:20px">${esc(top?.name||'—')}</div><div class="stat-foot">${top?pct(top):0}% win rate · ${top?kd(top):'0.00'} K/D</div></div>`;$('#matchBadge').textContent=state.matches.length}
function renderPlayers(){refreshTeams();const q=$('#search').value.toLowerCase(),team=$('#teamFilter').value,min=Number($('#minWin').value),sort=$('#sortBy').value;let rows=state.players.map((p,i)=>({...p,_i:i})).filter(p=>(!q||`${p.name} ${p.team}`.toLowerCase().includes(q))&&(team==='all'||p.team===team)&&pct(p)>=min);rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='kd'?Number(kd(b))-Number(kd(a)):sort==='winPct'?pct(b)-pct(a):b[sort]-a[sort]);$('#rowCount').textContent=rows.length;$('#empty').hidden=rows.length>0;$('#tableBody').innerHTML=rows.map((p,i)=>`<tr><td class="rank">${i+1}</td><td class="player-cell editable" contenteditable data-i="${p._i}" data-field="name">${esc(p.name)}</td><td class="team-cell editable" contenteditable data-i="${p._i}" data-field="team">${esc(p.team)}</td><td class="editable" contenteditable data-i="${p._i}" data-field="kills">${p.kills}</td><td class="editable" contenteditable data-i="${p._i}" data-field="deaths">${p.deaths}</td><td class="editable" contenteditable data-i="${p._i}" data-field="wins">${p.wins}</td><td class="editable" contenteditable data-i="${p._i}" data-field="losses">${p.losses}</td><td class="${pct(p)>=50?'positive':'neutral'}">${pct(p)}%</td><td class="${Number(kd(p))>=1?'positive':'neutral'}">${kd(p)}</td><td><button class="delete" data-delete="${p._i}" title="Delete player">×</button></td></tr>`).join('');renderCompareOptions()}
function teamStats(){const grouped={};state.matches.forEach(m=>{const key=[m.team,m.date,m.opponent,m.map,m.result].join('|');if(grouped[key])return;const t=grouped[m.team]??(grouped[m.team]={team:m.team,wins:0,losses:0});m.result==='W'?t.wins++:t.losses++});return Object.values(grouped).sort((a,b)=>{const ap=a.wins+a.losses,bp=b.wins+b.losses;return (bp?b.wins/bp:0)-(ap?a.wins/ap:0)})}
function renderTeams(){const data=teamStats();if(!data.length){$('#teamGrid').innerHTML='<div class="panel empty">Add match results to generate team standings.</div>';return}$('#teamGrid').innerHTML=data.map((t,i)=>{const total=t.wins+t.losses,rate=total?Math.round(t.wins/total*100):0;return`<article class="team-card"><div class="team-rank">#${i+1} · TEAM</div><div class="team-name">${esc(t.team)}</div><div class="team-record">${t.wins} wins <span>·</span> ${t.losses} losses <span>·</span> ${total} matches</div><div class="team-bar"><i style="width:${rate}%"></i></div><div class="team-rate"><span>Win rate</span><b>${rate}%</b></div></article>`}).join('')}
function renderMatches(){const ms=[...state.matches].sort((a,b)=>b.date.localeCompare(a.date));$('#matchEmpty').hidden=ms.length>0;$('#matchBody').innerHTML=ms.map((m,i)=>`<tr><td>${esc(m.date)}</td><td><b>${esc(m.player)}</b></td><td>${esc(m.team)}</td><td>${esc(m.opponent)}</td><td>${esc(m.map)}</td><td class="result-${m.result.toLowerCase()}">${m.result==='W'?'WIN':'LOSS'}${m.score?` <small>(${esc(m.score)})</small>`:''}</td><td>${m.kills} / ${m.deaths}</td><td><button class="delete" data-match-delete="${i}" title="Delete result">×</button></td></tr>`).join('')}
function renderMaps(){const maps={};state.matches.forEach(m=>{const x=maps[m.map]??(maps[m.map]={map:m.map,apps:0,wins:0,losses:0,kills:0,deaths:0});x.apps++;m.result==='W'?x.wins++:x.losses++;x.kills+=m.kills;x.deaths+=m.deaths});const data=Object.values(maps).sort((a,b)=>b.apps-a.apps);$('#mapEmpty').hidden=data.length>0;$('#mapBody').innerHTML=data.map(x=>{const rate=Math.round(x.wins/x.apps*100);return`<tr><td><b>${esc(x.map)}</b></td><td>${x.apps}</td><td class="positive">${x.wins}</td><td>${x.losses}</td><td class="${rate>=50?'positive':'neutral'}">${rate}%</td><td>${x.kills}</td><td>${x.deaths}</td><td>${x.deaths?(x.kills/x.deaths).toFixed(2):x.kills.toFixed(2)}</td></tr>`}).join('')}
function renderCompareOptions(){const a=$('#compareA'),b=$('#compareB'),oldA=a.value,oldB=b.value;a.innerHTML=state.players.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');b.innerHTML=a.innerHTML;a.value=state.players[oldA]?oldA:'0';b.value=state.players[oldB]?oldB:(state.players.length>1?'1':'0');renderCompare()}
function renderCompare(){const a=state.players[Number($('#compareA').value)],b=state.players[Number($('#compareB').value)];if(!a||!b){$('#compareStats').innerHTML='';return}const metric=(label,av,bv)=>`<div>${av}</div><div class="compare-labels"><b>${label}</b></div><div>${bv}</div>`;$('#compareStats').innerHTML=`<div class="compare-player"><b>${esc(a.name)}</b><small>${esc(a.team)}</small><strong>${pct(a)}%</strong></div><div class="compare-labels"><b>WIN %</b></div><div class="compare-player"><b>${esc(b.name)}</b><small>${esc(b.team)}</small><strong>${pct(b)}%</strong></div>${metric('KILLS',a.kills,b.kills)}${metric('DEATHS',a.deaths,b.deaths)}${metric('K/D',kd(a),kd(b))}${metric('WINS',a.wins,b.wins)}`}
function renderAll(){renderSummary();renderPlayers();renderTeams();renderMatches();renderMaps()}
function openModal(){const m=$('#modal');m.classList.add('open');$('#mDate').value=dateNow();const opts=state.players.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');$('#mPlayer').innerHTML=opts;const p=state.players[0];$('#mTeam').value=p?.team||'';$('#mPlayer').onchange=()=>$('#mTeam').value=state.players[Number($('#mPlayer').value)]?.team||'';$('#mTeam').value=p?.team||'';setTimeout(()=>$('#mOpponent').focus(),50)}
function closeModal(){$('#modal').classList.remove('open')}
function addPlayer(){snapshot();state.players.unshift({name:'New player',team:'New team',kills:0,deaths:0,wins:0,losses:0});save();renderAll();setTimeout(()=>document.querySelector('.editable')?.focus(),50)}
$('#tableBody').addEventListener('focusout',e=>{if(!e.target.matches('.editable'))return;snapshot();const i=Number(e.target.dataset.i),f=e.target.dataset.field;state.players[i][f]=['kills','deaths','wins','losses'].includes(f)?num(e.target.textContent.trim()):e.target.textContent.trim();save();renderAll()});$('#tableBody').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;snapshot();state.players.splice(Number(b.dataset.delete),1);save();renderAll()});$('#matchBody').addEventListener('click',e=>{const b=e.target.closest('[data-match-delete]');if(!b)return;const sorted=[...state.matches].sort((a,b)=>b.date.localeCompare(a.date));const m=sorted[Number(b.dataset.matchDelete)];const i=state.matches.indexOf(m);snapshot();const p=state.players.find(x=>x.name===m.player&&x.team===m.team);if(p){p.kills=Math.max(0,p.kills-m.kills);p.deaths=Math.max(0,p.deaths-m.deaths);m.result==='W'?p.wins=Math.max(0,p.wins-1):p.losses=Math.max(0,p.losses-1)}state.matches.splice(i,1);save();renderAll()});
['search','teamFilter','minWin','sortBy'].forEach(id=>$('#'+id).addEventListener('input',renderPlayers));document.querySelectorAll('th[data-key]').forEach(th=>th.addEventListener('click',()=>{$('#sortBy').value=th.dataset.key;renderPlayers()}));$('#clearFilters').onclick=()=>{$('#search').value='';$('#teamFilter').value='all';$('#minWin').value='0';$('#sortBy').value='winPct';renderPlayers()};['addMatchBtn','matchesAddBtn','teamsAddBtn'].forEach(id=>$('#'+id).onclick=openModal);$('#addPlayerBtn').onclick=addPlayer;$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#matchForm').onsubmit=e=>{e.preventDefault();const i=Number($('#mPlayer').value),p=state.players[i],m={date:$('#mDate').value,player:p.name,team:$('#mTeam').value.trim(),opponent:$('#mOpponent').value.trim(),map:$('#mMap').value.trim(),result:$('#mResult').value,kills:num($('#mKills').value),deaths:num($('#mDeaths').value),score:$('#mScore').value.trim()};if(!m.player||!m.team||!m.opponent||!m.map)return;snapshot();p.team=m.team;p.kills+=m.kills;p.deaths+=m.deaths;m.result==='W'?p.wins++:p.losses++;state.matches.push(m);save();renderAll();closeModal();switchView('matches')};
function switchView(view){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view+'View'));window.scrollTo({top:300,behavior:'smooth'})}document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));$('#compareA').onchange=renderCompare;$('#compareB').onchange=renderCompare;$('#undoBtn').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());save();renderAll();$('#undoBtn').disabled=!history.length};$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('r6-theme',document.body.classList.contains('light')?'light':'dark')};$('#resetBtn')?.addEventListener('click',()=>{});
function csv(){return['name,team,kills,deaths,wins,losses',...state.players.map(p=>[p.name,p.team,p.kills,p.deaths,p.wins,p.losses].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n')};function parseCSV(text){const lines=text.trim().split(/\r?\n/);return lines.length<2?[]:lines.slice(1).map(line=>{const v=[...line.matchAll(/(?:^|,)\s*(?:"((?:[^"]|"")*)"|([^,]*))/g)].map(m=>(m[1]??m[2]??'').replaceAll('""','"').trim());return{name:v[0]||'Unnamed player',team:v[1]||'Unassigned',kills:num(v[2]),deaths:num(v[3]),wins:num(v[4]),losses:num(v[5])}}).filter(p=>p.name)}
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='r6-stage-2-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=f.name.endsWith('.json')?JSON.parse(r.result):{players:parseCSV(r.result),matches:[]};if(data.players?.length){snapshot();state={players:data.players,matches:data.matches||[]};save();renderAll()}}catch(err){alert('Could not read that backup file.')}};r.readAsText(f);e.target.value=''};
const saved=localStorage.getItem('r6-stage2-time');if(saved)$('#lastSaved').textContent=new Date(saved).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(localStorage.getItem('r6-theme')==='light')document.body.classList.add('light');renderAll();
